// src/views/Products.vue
<template>
  <div>
    <h1>Product Categories</h1>
    <ul>
      <li v-for="category in categories" :key="category">{{ category }}</li>
    </ul>
  </div>
</template>

<script>
export default {
  data() {
    return {
      categories: ['Electronics', 'Clothing', 'Books'],
    };
  },
};
</script>

// products.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-products',
  templateUrl: './products.component.html',
})
export class ProductsComponent {
  categories = ['Electronics', 'Clothing', 'Books'];
}

<div>
  <h1>Product Categories</h1>
  <ul>
    <li *ngFor="let category of categories">{{ category }}</li>
  </ul>
</div>
